### ISSUE TITLE
Unable to build/make ghost on Windows and Linux

### ISSUE THREAD

**Issue by u2u4** [maxemann96/ghostpp#5]
I have tried to build ghost using visual studio however I get an error when trying to build with boost v1.38 included [error log](https://ghostbin.com/paste/6npnk) am I using the wrong boost version?.

I have also tried to run `cmake -G "MSYS Makefiles" && make install` on bncsutil, StormLib and CascLib however when I try to make ghost I get the following.

```
maxemann96-ghostpp\ghost>make all

g++ -o bncsutilinterface.o  -O3 -DGHOST_MYSQL -I. -c bncsutilinterface.cpp
In file included from includes.h:27,
                 from ghost.h:24,
                 from bncsutilinterface.cpp:21:
ms_stdint.h:33:2: error: #error "Use this header only with Microsoft Visual C++ compilers!"
 #error "Use this header only with Microsoft Visual C++ compilers!"
  ^~~~~
In file included from C:/msys64/mingw64/lib/gcc/x86_64-w64-mingw32/8.2.0/include/stdint.h:9,
                 from C:/msys64/mingw64/include/c++/8.2.0/cstdint:41,
                 from C:/msys64/mingw64/include/c++/8.2.0/bits/char_traits.h:501,
                 from C:/msys64/mingw64/include/c++/8.2.0/ios:40,
                 from C:/msys64/mingw64/include/c++/8.2.0/istream:38,
                 from C:/msys64/mingw64/include/c++/8.2.0/fstream:38,
                 from includes.h:34,
                 from ghost.h:24,
                 from bncsutilinterface.cpp:21:
C:/msys64/mingw64/x86_64-w64-mingw32/include/stdint.h:35:21: error: conflicting declaration 'typedef signed char int8_t'
 typedef signed char int8_t;
                     ^~~~~~
In file included from includes.h:27,
                 from ghost.h:24,
                 from bncsutilinterface.cpp:21:
ms_stdint.h:72:27: note: previous declaration as 'typedef char int8_t'
 typedef __int8            int8_t;
                           ^~~~~~
In file included from C:/msys64/mingw64/lib/gcc/x86_64-w64-mingw32/8.2.0/include/stdint.h:9,
                 from C:/msys64/mingw64/include/c++/8.2.0/cstdint:41,
                 from C:/msys64/mingw64/include/c++/8.2.0/bits/char_traits.h:501,
                 from C:/msys64/mingw64/include/c++/8.2.0/ios:40,
                 from C:/msys64/mingw64/include/c++/8.2.0/istream:38,
                 from C:/msys64/mingw64/include/c++/8.2.0/fstream:38,
                 from includes.h:34,
                 from ghost.h:24,
                 from bncsutilinterface.cpp:21:
C:/msys64/mingw64/x86_64-w64-mingw32/include/stdint.h:45:21: error: conflicting declaration 'typedef signed char int_least8_t'
 typedef signed char int_least8_t;
                     ^~~~~~~~~~~~
In file included from includes.h:27,
                 from ghost.h:24,
                 from bncsutilinterface.cpp:21:
ms_stdint.h:82:19: note: previous declaration as 'typedef int8_t int_least8_t'
 typedef int8_t    int_least8_t;
                   ^~~~~~~~~~~~
In file included from C:/msys64/mingw64/lib/gcc/x86_64-w64-mingw32/8.2.0/include/stdint.h:9,
                 from C:/msys64/mingw64/include/c++/8.2.0/cstdint:41,
                 from C:/msys64/mingw64/include/c++/8.2.0/bits/char_traits.h:501,
                 from C:/msys64/mingw64/include/c++/8.2.0/ios:40,
                 from C:/msys64/mingw64/include/c++/8.2.0/istream:38,
                 from C:/msys64/mingw64/include/c++/8.2.0/fstream:38,
                 from includes.h:34,
                 from ghost.h:24,
                 from bncsutilinterface.cpp:21:
C:/msys64/mingw64/x86_64-w64-mingw32/include/stdint.h:58:21: error: conflicting declaration 'typedef signed char int_fast8_t'
 typedef signed char int_fast8_t;
                     ^~~~~~~~~~~
In file included from includes.h:27,
                 from ghost.h:24,
                 from bncsutilinterface.cpp:21:
ms_stdint.h:92:19: note: previous declaration as 'typedef int8_t int_fast8_t'
 typedef int8_t    int_fast8_t;
                   ^~~~~~~~~~~
make: *** [Makefile:46: bncsutilinterface.o] Error 1
```

**Comment by u2u4** [comment]
I have just tried to make ghost on linux following the readme and once I get to make in the ghost folder it fails to build.
```
make
g++ -o bncsutilinterface.o  -O3 -DGHOST_MYSQL -I. -c bncsutilinterface.cpp
g++ -o bnet.o  -O3 -DGHOST_MYSQL -I. -c bnet.cpp
g++ -o bnetprotocol.o  -O3 -DGHOST_MYSQL -I. -c bnetprotocol.cpp
g++ -o bnlsclient.o  -O3 -DGHOST_MYSQL -I. -c bnlsclient.cpp
g++ -o bnlsprotocol.o  -O3 -DGHOST_MYSQL -I. -c bnlsprotocol.cpp
g++ -o commandpacket.o  -O3 -DGHOST_MYSQL -I. -c commandpacket.cpp
g++ -o config.o  -O3 -DGHOST_MYSQL -I. -c config.cpp
g++ -o crc32.o  -O3 -DGHOST_MYSQL -I. -c crc32.cpp
g++ -o csvparser.o  -O3 -DGHOST_MYSQL -I. -c csvparser.cpp
g++ -o game.o  -O3 -DGHOST_MYSQL -I. -c game.cpp
g++ -o game_admin.o  -O3 -DGHOST_MYSQL -I. -c game_admin.cpp
g++ -o game_base.o  -O3 -DGHOST_MYSQL -I. -c game_base.cpp
g++ -o gameplayer.o  -O3 -DGHOST_MYSQL -I. -c gameplayer.cpp
g++ -o gameprotocol.o  -O3 -DGHOST_MYSQL -I. -c gameprotocol.cpp
g++ -o gameslot.o  -O3 -DGHOST_MYSQL -I. -c gameslot.cpp
g++ -o ghost.o  -O3 -DGHOST_MYSQL -I. -c ghost.cpp
g++ -o ghostdb.o  -O3 -DGHOST_MYSQL -I. -c ghostdb.cpp
g++ -o ghostdbmysql.o  -O3 -DGHOST_MYSQL -I. -c ghostdbmysql.cpp
g++ -o ghostdbsqlite.o  -O3 -DGHOST_MYSQL -I. -c ghostdbsqlite.cpp
g++ -o gpsprotocol.o  -O3 -DGHOST_MYSQL -I. -c gpsprotocol.cpp
g++ -o language.o  -O3 -DGHOST_MYSQL -I. -c language.cpp
g++ -o map.o  -O3 -DGHOST_MYSQL -I. -c map.cpp
g++ -o packed.o  -O3 -DGHOST_MYSQL -I. -c packed.cpp
g++ -o replay.o  -O3 -DGHOST_MYSQL -I. -c replay.cpp
g++ -o savegame.o  -O3 -DGHOST_MYSQL -I. -c savegame.cpp
g++ -o sha1.o  -O3 -DGHOST_MYSQL -I. -c sha1.cpp
g++ -o socket.o  -O3 -DGHOST_MYSQL -I. -c socket.cpp
g++ -o stats.o  -O3 -DGHOST_MYSQL -I. -c stats.cpp
g++ -o statsdota.o  -O3 -DGHOST_MYSQL -I. -c statsdota.cpp
g++ -o statsw3mmd.o  -O3 -DGHOST_MYSQL -I. -c statsw3mmd.cpp
g++ -o util.o  -O3 -DGHOST_MYSQL -I. -c util.cpp
gcc -o sqlite3.o  -O3 -DGHOST_MYSQL -I. -c sqlite3.c
g++ -o ./ghost++ bncsutilinterface.o bnet.o bnetprotocol.o bnlsclient.o bnlsprotocol.o commandpacket.o config.o crc32.o csvparser.o game.o game_admin.o game_base.o gameplayer.o gameprotocol.o gameslot.o ghost.o ghostdb.o ghostdbmysql.o ghostdbsqlite.o gpsprotocol.o language.o map.o packed.o replay.o savegame.o sha1.o socket.o stats.o statsdota.o statsw3mmd.o util.o sqlite3.o -L. -lbncsutil -lpthread -ldl -lstorm -lcasc -lz -lmysqlclient -lboost_date_time -lboost_system -lboost_filesystem -lgmp -lbz2 -lrt -lboost_thread
//usr/local/lib/libcasc.a(Common.cpp.o): In function `CheckWildCard(char const*, char const*)':
Common.cpp:(.text+0xf0e): multiple definition of `CheckWildCard(char const*, char const*)'
//usr/local/lib/libstorm.a(SFileFindFile.cpp.o):SFileFindFile.cpp:(.text+0x4c): first defined here
collect2: error: ld returned 1 exit status
Makefile:40: recipe for target 'ghost++' failed
make: *** [ghost++] Error 1

```

**Comment by maxemann96** [comment]
Seems like this: https://github.com/ladislav-zezula/StormLib/issues/138. Do you updated the casc and the stormlib installed on your pc? (The copy of them in this repository changed to a newer version). Also im sorry for the late answer, but github does not send me any email notification (i think this is debt by the github system status of 22.10 https://status.github.com/messages)

**Comment by BasedOnPixels** [comment]
Sorry to barge in here, I'm having the same issue. 
Are we supposed to download the latest versions of StormLib and CascLib from ladislav?

**Comment by maxemann96** [comment]
No, i included the latest version in this repository. Can you pls add some more information about your system? Perfect to test for me could be a Dockerfile describing a system where the build is crashing

**Comment by BasedOnPixels** [comment]
I'm using Lubuntu 18.04.1 LTS
https://lubuntu.me/downloads/
Is there anything else you need to know? I'm not sure what a Dockerfile is, could you explain perhaps?

**Comment by maxemann96** [comment]
Ok, i can reproduce that, working on a fix

**Comment by maxemann96** [comment]
Can you confirm this README fix, is fixing your problem?
(In the step where you build casclib, remove the additional parameters starting with -D...)

**Comment by BasedOnPixels** [comment]
It compiles fine now, but I can't run ghost++
![grafik](https://user-images.githubusercontent.com/13744383/47623877-8d3abb00-db16-11e8-9418-d0f10796af08.png)

**Comment by maxemann96** [comment]
Do you set your ld_library_path environment variable correctly?
See https://help.ubuntu.com/community/EnvironmentVariables for more info

**Comment by BasedOnPixels** [comment]
I think it's right, I don't see anything wrong with it

![grafik](https://user-images.githubusercontent.com/13744383/47654212-9feed780-db8a-11e8-9e8b-343c5fee9811.png)

**Comment by maxemann96** [comment]
Can you try a `ldconfig` and then restart ghostpp?

**Comment by maxemann96** [comment]
@CookiePl0x Does this work for you?

**Comment by BasedOnPixels** [comment]
Sorry for the late reply, I didn't get or missed the notification. Yeah this actually fixed my issue, just putting in the command resolved the problem. 
Thanks for the help!
